routes/admin.php
<?php

use App\Http\Controllers\Api\ShippingServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('users', 'UserController');
Route::resource('packages', 'PackageController');
Route::resource('equipment', 'EquipmentController');

Route::get('api/package/tracking/{package}', [ShippingServiceController::class, 'getStatus'])->name('api.package.track');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Intervention\Image\Constraint;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('dashboard');

/**
 * Handle serving up images in a standard way
 */
Route::get('/files/{storage}/{hash_name}/{width?}', function ($storage, $hash_name, $width = 200) {
    // Using cache here to service up a cached version of the image based on hash
    // is safe because the hash is unique and gets changed out when a new image is uploaded
    return Cache::remember("{$hash_name}/{$width}", 1, function () use ($storage, $hash_name, $width) {
        $file      = \App\Models\File::where('hash_name', $hash_name)->first();
        $file_path = Arr::get($file, 'file_name');

        // if the image does not exist default it to something else
        if (!$file || !Storage::disk($storage)->exists($file_path)) {
            $file_path = 'placeholder.png';
        }

        return Image::make(Storage::disk($storage)->get($file_path))
                    ->resize($width, $width, function (Constraint $constraint) {
                        $constraint->aspectRatio();
                    })
                    ->response();
    });
})->name('file.show');

app/Models/Equipment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Equipment
 * @property Option brand
 * @property Option model
 * @package App\Models
 */
class Equipment extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'description',
        'brand_id',
        'model_id',
    ];

    public function getBrandNameAttribute()
    {
        return $this->brand->label ?: '';
    }

    public function getModelNameAttribute()
    {
        return $this->model->label ?: '';
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function brand()
    {
        return $this->hasOne(Option::class, 'id', 'brand_id');
    }

    public function model()
    {
        return $this->hasOne(Option::class, 'id', 'model_id');
    }
}

app/Http/Controllers/Admin/EquipmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Equipment;
use Illuminate\Http\Request;

class EquipmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $equipment = Equipment::orderBy('user_id', 'desc')->paginate(request('per_page', 15));

        return view('equipment.admin-index', compact('equipment'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\Response
     */
    public function show(Equipment $equipment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\Response
     */
    public function edit(Equipment $equipment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Equipment $equipment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Equipment $equipment)
    {
        //
    }
}

app/Http/Controllers/Authed/EquipmentController.php
<?php

namespace App\Http\Controllers\Authed;

use App\Http\Controllers\Controller;
use App\Models\Dropdown;
use App\Models\Equipment;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Str;

class EquipmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $equipment = auth()->user()->equipment;

        return view('equipment.index', compact('equipment'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        return view('equipment.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $data = $request->except('_token');

        if ($request->get('brand_other')) {
            $option = Dropdown::whereSlug('brand')->first()->options()->firstOrCreate(['slug' => Str::slug($request->get('brand_other'))], [
                'label' => $request->get('brand_other'),
            ]);

            $data['brand_id'] = $option->id;
        }

        if ($request->get('model_other')) {
            $option = Dropdown::whereSlug('model')->first()->options()->firstOrCreate(['slug' => Str::slug($request->get('model_other'))], [
                'label'     => $request->get('model_other'),
                'parent_id' => $data['brand_id'],
            ]);

            $data['model_id'] = $option->id;
        }

        auth()->user()->equipment()->create($data);

        session()->flash('saved');

        return redirect()->route('authed.equipment.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Equipment $equipment
     * @return Factory|View
     */
    public function show(Equipment $equipment)
    {
        return view('equipment.show', compact('equipment'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Equipment $equipment
     * @return Factory|View
     */
    public function edit(Equipment $equipment)
    {
        return view('equipment.edit', compact('equipment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request   $request
     * @param Equipment $equipment
     * @return Response
     */
    public function update(Request $request, Equipment $equipment)
    {
        $data = $request->all();

        if ($request->get('brand_other')) {
            $option = Dropdown::whereSlug('brand')->first()->options()->firstOrCreate(['slug' => Str::slug($request->get('brand_other'))], [
                'label' => $request->get('brand_other'),
            ]);

            $data['brand_id'] = $option->id;
        }

        if ($request->get('model_other')) {
            $option = Dropdown::whereSlug('model')->first()->options()->firstOrCreate(['slug' => Str::slug($request->get('model_other'))], [
                'label'     => $request->get('model_other'),
                'parent_id' => $data['brand_id'],
            ]);

            $data['model_id'] = $option->id;
        }

        $equipment->update($data);

        session()->flash('saved');

        return redirect()->route('authed.equipment.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Equipment $equipment
     * @return Response
     */
    public function destroy(Equipment $equipment)
    {
        $equipment->delete();

        return redirect()->route('authed.equipment.index');
    }
}

resources/views/equipment/admin-index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        Total results: {{$equipment->total()}} <br>
        {!! $equipment->links() !!}

        <table class="table table-hover">
            <tr>
                <th>User</th>
                <th>Description</th>
                <th>Saved</th>
                <th>Brand / Model</th>
            </tr>
            @forelse($equipment as $item)
                <tr>
                    <td><a href="{{route('admin.users.show', $item->user_id)}}">{{$item->user_id}} - {{$item->user->name}}</a></td>
                    <td>{{Str::limit($item->AAA)}}</td>
                    <td>{{$item->updated_at}}</td>
                    <td>{{$item->brand_name}} / {{$item->model_name}}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="100">
                        Nothing tracked
                    </td>
                </tr>
            @endforelse
        </table>
    </div>
@endsection

resources/views/equipment/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        {!! Form::open(['route' => 'authed.equipment.store', 'method' => 'post']) !!}

        @include('equipment.fields')

        @include('partials.form-buttons')

        {!! Form::close() !!}
    </div>
@endsection

resources/views/equipment/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        {!! Form::model($equipment, ['route' => ['authed.equipment.update', $equipment], 'method' => 'put']) !!}

        @include('equipment.fields')

        @include('partials.form-buttons')

        {!! Form::close() !!}
    </div>
@endsection

resources/views/equipment/fields.blade.php
@include('partials.form-errors')

<div class="row">
    <div class="col-md-12">
        <equipment
            old_brand="{{Form::getValueAttribute('brand_id')}}"
            old_model="{{Form::getValueAttribute('model_id')}}"
            :brand_options="{!! str_replace('"', "'", \App\Models\Dropdown::findBySlug('brand')->toJson()) !!}"
            :model_options="{!! str_replace('"', "'", \App\Models\Dropdown::findBySlug('model')->toJson()) !!}"
        ></equipment>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for="description">Description</label>
            {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

resources/views/equipment/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        <a href="{{route('authed.equipment.create')}}" class="btn btn-primary">Create</a>
        <hr>
        <table class="table table-hover table-stripped">
            <thead>
            <tr>
                <th>id</th>
                <th>Brand/ Model</th>
                <th>description</th>
                <th>created</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @forelse($equipment as $equip)
                <tr>
                    <td>
                        {{$equip->id}}
                    </td>
                    <td>
                        {{$equip->brand_name}} / {{$equip->model_name}}
                    </td>
                    <td>
                        {{Str::limit($equip->id)}}
                    </td>
                    <td>
                        {{$equip->created_at}}
                    </td>
                    <td>
                        <a href="{{route('authed.equipment.edit', $equip)}}" class="btn btn-primary">Edit</a>
                        <btn-confirm form_selector="#equipment-{{$equip->id}}-delete" label="Delete"></btn-confirm>
                        {!! Form::open(['id' => "equipment-{$equip->id}-delete", 'class' => 'hidden', 'route' => ['authed.equipment.destroy', $equip], 'method' => 'delete']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="100">
                        No Equipment
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
@endsection

resources/views/equipment/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        Waiting for content . . .
    </div>
@endsection