routes/admin.php
<?php

use App\Http\Controllers\Api\ShippingServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('users', 'UserController');
Route::resource('packages', 'PackageController');
Route::resource('equipment', 'EquipmentController');

Route::get('api/package/tracking/{package}', [ShippingServiceController::class, 'getStatus'])->name('api.package.track');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Intervention\Image\Constraint;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('dashboard');

/**
 * Handle serving up images in a standard way
 */
Route::get('/files/{storage}/{hash_name}/{width?}', function ($storage, $hash_name, $width = 200) {
    // Using cache here to service up a cached version of the image based on hash
    // is safe because the hash is unique and gets changed out when a new image is uploaded
    return Cache::remember("{$hash_name}/{$width}", 1, function () use ($storage, $hash_name, $width) {
        $file      = \App\Models\File::where('hash_name', $hash_name)->first();
        $file_path = Arr::get($file, 'file_name');

        // if the image does not exist default it to something else
        if (!$file || !Storage::disk($storage)->exists($file_path)) {
            $file_path = 'placeholder.png';
        }

        return Image::make(Storage::disk($storage)->get($file_path))
                    ->resize($width, $width, function (Constraint $constraint) {
                        $constraint->aspectRatio();
                    })
                    ->response();
    });
})->name('file.show');

app/Models/Equipment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Equipment
 * @property Option brand
 * @property Option model
 * @package App\Models
 */
class Equipment extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'description',
        'brand_id',
        'model_id',
    ];

    public function getBrandNameAttribute()
    {
        return $this->brand->label ?: '';
    }

    public function getModelNameAttribute()
    {
        return $this->model->label ?: '';
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function brand()
    {
        return $this->hasOne(Option::class, 'id', 'brand_id');
    }

    public function model()
    {
        return $this->hasOne(Option::class, 'id', 'model_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * @property string            name
 * @property string            first_name
 * @property string            last_name
 * @property File|MorphOne     profile_image
 * @property Equipment|HasMany equipment
 * @property int               id
 */
class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'is_admin',
        'first_name',
        'last_name',
        'email',
        'password',
    ];

    protected $appends = ['name'];

    protected $cast = [
        'is_admin' => 'boolean',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getNameAttribute(): string
    {
        return sprintf('%s %s', $this->first_name, $this->last_name);
    }

    public function getSmProfileImageUrlAttribute()
    {
        if (!$this->profile_image) {
            return route('file.show', ['profile_images', 'undefined']) . '/50';
        }

        return "{$this->profile_image->url}/50";
    }

    public function getProfileImageUrlAttribute()
    {
        if (!$this->profile_image) {
            return route('file.show', ['profile_images', 'undefined']);
        }

        return "{$this->profile_image->url}/200";
    }

    public function equipment(): HasMany
    {
        return $this->hasMany(Equipment::class);
    }

    public function social_media(): HasMany
    {
        return $this->hasMany(SocialMedia::class);
    }

    public function packages(): HasMany
    {
        return $this->hasMany(Package::class);
    }

    public function profile_image()
    {
        return $this->morphOne(File::class, 'fileable');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Models\User;
use Auth;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $users = User::paginate(request('per_page', 15));

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $user = User::create($request->except('password'));

        if ($request->has('password')) {
            $user->update(['password' => bcrypt($request->get('password'))]);
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return Factory|View
     */
    public function show(User $user)
    {
        $user->loadMissing(['packages.service', 'social_media.service', 'equipment']);

        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return Factory|View
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param User    $user
     * @return RedirectResponse
     */
    public function update(Request $request, User $user)
    {
        $user->update($request->except('password'));

        if ($request->has('password')) {
            $user->update(['password' => bcrypt($request->get('password'))]);
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return Response
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->back();
    }

    // Admin profile controller functions.
    public function profile()
    {
        $user = Auth::user();

        return view('users.profile', compact('user'));
    }

    public function profile_save(UserRequest $request)
    {
        Auth::user()->update($request->except(['password']));

        if ($request->has('password')) {
            Auth::user()->update(['password' => bcrypt($request->get('password'))]);
        }

        session()->flash('updated_message');

        return redirect()->back();
    }
}

app/Http/Controllers/Authed/UserController.php
<?php

namespace App\Http\Controllers\Authed;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Jobs\ImageUploadJob;
use App\Models\SocialMediaService;
use App\Models\User;
use Auth;

class UserController extends Controller
{
    public function profile()
    {
        $user = Auth::user();

        /** @var User $user */
        $social_media = $user->social_media()->with('service')->get()->keyBy('service.slug');

        return view('users.profile', compact('user', 'social_media'));
    }

    public function profile_save(UserRequest $request)
    {
        $request_image = $request->file('profile_image');
        $image_name    = auth()->id() . '/profile_image';

        if ($request_image) {
            ImageUploadJob::dispatchNow($request_image, $image_name, auth()->user());
        }

        /** @var User $user */
        $user = auth()->user();

        Auth::user()->update($request->except(['password', 'is_admin']));

        $services = SocialMediaService::all()->keyBy('slug');

        foreach ($request->get('social_media', []) as $service => $url) {
            if (!$url) {
                continue;
            }
            $user->social_media()->updateOrCreate(['social_media_service_id' => $services[$service]->id], [
                'url' => $url,
            ]);
        }

        if (($request->get('change_password') == '1') && $request->has('password')) {
            Auth::user()->update(['password' => bcrypt($request->get('password'))]);
        }

        session()->flash('saved');

        return redirect()->route('dashboard');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        {!! Form::open(['route' => ['admin.user.store'], 'method'=> 'post']) !!}

        @include('users.fields')

        @include('partials.form-buttons')

        {!! Form::close() !!}

    </div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        {!! Form::model($user, ['route' => ['admin.users.update', $user], 'method'=> 'put']) !!}

        @include('users.fields')

        @include('partials.form-buttons')

        {!! Form::close() !!}

    </div>

@endsection

resources/views/users/fields.blade.php
@include('partials.form-errors')

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for="is_admin" class="text-danger">
                {!! Form::checkbox('is_admin') !!} Is Admin
            </label>
        </div>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-md-6">

        <div class="form-group">
            <label for="first_name">First Name</label>
            {!! Form::text('first_name', null, ['class' => 'form-control']) !!}
            @error('first_name')
            <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
            @enderror
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label for="last_name">Last Name</label>
            {!! Form::text('last_name', null, ['class' => 'form-control']) !!}
            @error('last_name')
            <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
            @enderror
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for="email">Email</label>
            {!! Form::email('email', null, ['class' => 'form-control']) !!}
            @error('email')
            <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
            @enderror
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="password">Password</label>
            {!! Form::password('password', ['class' => 'form-control']) !!}
            @error('password')
            <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
            @enderror
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label for="first_name">Password confirm</label>
            {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
            @error('password_confirmation')
            <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
            @enderror
        </div>
    </div>
</div>

resources/views/users/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">

        Total results: {{$users->total()}} <br>
        {!! $users->links() !!}

        <table class="table table-hover table-stripped">
            <thead>
            <tr>
                <th></th>
                <th>id</th>
                <th>name</th>
                <th>email</th>
                <th>created</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @forelse($users as $user)
                <tr>
                    <td><img src="{{$user->sm_profile_image_url}}" alt="Profile image" class="rounded-circle"/></td>
                    <td>{{$user->id}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->created_at}}</td>
                    <td>
                        <a href="{{route('admin.users.edit', $user)}}" class="btn btn-primary">Edit</a>
                        <a href="{{route('admin.users.show', $user)}}" class="btn btn-secondary">Show</a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="100">
                        No Users
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
@endsection

resources/views/users/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        {!! Form::model($user, ['route' => ['authed.user.profile.save'], 'method'=> 'put', 'files' => true]) !!}

        @include('partials.form-errors')

        <div class="row">
            <div class="offset-md-6 col-md-6">
                @if($user->profile_image_url)
                <img src="{{$user->profile_image_url}}" alt="Profile image" />
                @endif

                <div class="form-group">
                    <label for="profile_image">Profile image</label>
                    <input type="file" class="form-control-file" name="profile_image" id="profile_image" placeholder="Profile image" aria-describedby="profile_image_help">
                    <small id="profile_image_help" class="form-text text-muted">Profile image</small>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">

                <div class="form-group">
                    <label for="first_name">First Name</label>
                    {!! Form::text('first_name', null, ['class' => 'form-control']) !!}
                    @error('first_name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    {!! Form::text('last_name', null, ['class' => 'form-control']) !!}
                    @error('last_name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="email">Email</label>
                    {!! Form::email('email', null, ['class' => 'form-control']) !!}
                    @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
        </div>

        @if(\App\Models\SocialMediaService::count())
            <section id="social-media">
                <div class="row">

                    @foreach(\App\Models\SocialMediaService::all() as $service)
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="{{$service->slug}}">{{$service->label}}</label>
                                {!! Form::text("social_media[{$service->slug}]", \Illuminate\Support\Arr::get($social_media, "{$service->slug}.url", ''), ['id' => $service->slug, 'class' => 'form-control']) !!}
                            </div>
                        </div>
                    @endforeach
                </div>
            </section>
        @endif

        <div class="row" style="display: none;" id="password-section">
            <input type="hidden" name="change_password" value="0"/>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="password">Password</label>
                    {!! Form::password('password', ['class' => 'form-control']) !!}
                    @error('password')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="first_name">Password confirm</label>
                    {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
                    @error('password_confirmation')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
        </div>

        @include('partials.form-buttons', ['changePassword' => true])

        {!! Form::close() !!}

    </div>

@endsection

@section('js')
    <script type="text/javascript">
        $(function () {
            $("#changePassword").click(function(){
                $("#password-section").fadeToggle('fast');

                const element = $("[name='change_password']");

                element.val(
                    element.val() != '1'? '1': '0'
                )
            })
        });
    </script>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div>
                    <img src="{{$user->sm_profile_image_url}}" alt="Profile image" class="rounded-circle"/>
                </div>
                <div>Name: {{$user->name}}</div>
                <div>Email: {{$user->email}}</div>
                <div>Saved: {{$user->updated_at}}</div>
            </div>
            <div class="col-md-6">

                <table class="table table-hover">
                    <tbody>
                    @forelse($user->social_media as $item)
                        <tr>
                            <td>
                                <strong>{{$item->name}}</strong> - {{$item->url}}
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td>No social media entered</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>

            </div>
        </div>

        <div class="row mt-5">
            <div class="col-md-6">
                <h3>Equipment</h3>
                <hr>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Brand / Model</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($user->equipment as $item)
                        <tr>
                            <td>
                                {{$item->brand_name}} / {{$item->model_name}}
                            </td>
                        </tr>

                    @empty
                        <tr>
                            <td>Nothing logged</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <h3>Packages</h3>
                <hr>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Item</th>
                            <th>Description</th>
                            <th>QTY</th>
                            <th>Shipping Service</th>
                            <th>Tracking number</th>
                            <th>Shipped Date</th>
                            <th>Es. Delivery Date</th>
                            <th>Delivered Date</th>
                            <th>Last Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            @forelse($user->packages as $item)
                                <td>{{$item->item}}</td>
                                <td>{{Str::limit($item->description)}}</td>
                                <td>{{$item->qty}}</td>
                                <td>{{$item->shipping_service_name}}</td>
                                <td>{{$item->tracking_number}}</td>
                                <td>{{$item->ship_date}}</td>
                                <td>{{$item->delivered_date}}</td>
                                <td>{{$item->estimated_delivery_date}}</td>
                                <td>{{$item->last_status}}</td>
                            @empty
                                <td colspan="100">Nothing logged</td>
                            @endforelse
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection