routes/admin.php
<?php

use App\Http\Controllers\Api\ShippingServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('users', 'UserController');
Route::resource('packages', 'PackageController');
Route::resource('equipment', 'EquipmentController');

Route::get('api/package/tracking/{package}', [ShippingServiceController::class, 'getStatus'])->name('api.package.track');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Intervention\Image\Constraint;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('dashboard');

/**
 * Handle serving up images in a standard way
 */
Route::get('/files/{storage}/{hash_name}/{width?}', function ($storage, $hash_name, $width = 200) {
    // Using cache here to service up a cached version of the image based on hash
    // is safe because the hash is unique and gets changed out when a new image is uploaded
    return Cache::remember("{$hash_name}/{$width}", 1, function () use ($storage, $hash_name, $width) {
        $file      = \App\Models\File::where('hash_name', $hash_name)->first();
        $file_path = Arr::get($file, 'file_name');

        // if the image does not exist default it to something else
        if (!$file || !Storage::disk($storage)->exists($file_path)) {
            $file_path = 'placeholder.png';
        }

        return Image::make(Storage::disk($storage)->get($file_path))
                    ->resize($width, $width, function (Constraint $constraint) {
                        $constraint->aspectRatio();
                    })
                    ->response();
    });
})->name('file.show');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * @property string            name
 * @property string            first_name
 * @property string            last_name
 * @property File|MorphOne     profile_image
 * @property Equipment|HasMany equipment
 * @property int               id
 */
class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'is_admin',
        'first_name',
        'last_name',
        'email',
        'password',
    ];

    protected $appends = ['name'];

    protected $cast = [
        'is_admin' => 'boolean',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getNameAttribute(): string
    {
        return sprintf('%s %s', $this->first_name, $this->last_name);
    }

    public function getSmProfileImageUrlAttribute()
    {
        if (!$this->profile_image) {
            return route('file.show', ['profile_images', 'undefined']) . '/50';
        }

        return "{$this->profile_image->url}/50";
    }

    public function getProfileImageUrlAttribute()
    {
        if (!$this->profile_image) {
            return route('file.show', ['profile_images', 'undefined']);
        }

        return "{$this->profile_image->url}/200";
    }

    public function equipment(): HasMany
    {
        return $this->hasMany(Equipment::class);
    }

    public function social_media(): HasMany
    {
        return $this->hasMany(SocialMedia::class);
    }

    public function packages(): HasMany
    {
        return $this->hasMany(Package::class);
    }

    public function profile_image()
    {
        return $this->morphOne(File::class, 'fileable');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<div id="app">
    @include('layouts.top-nav')

    <main class="py-4">
        @yield('content')
    </main>
</div>
<!-- Scripts -->
<script src="{{ mix('js/app.js') }}"></script>
<script type="text/javascript">
    @if(session()->get('saved'))
        window.toastr['success']('Thank you.', 'Saved!');
    @endif
</script>
@yield('js')
</body>
</html>

resources/views/layouts/top-nav.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        @guest
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        @else
            <a class="navbar-brand" href="{{ route('dashboard') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        @endguest
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                @can('admin')
                    <li class="nav-item">
                        <a class="nav-link text-danger" href="{{ route('admin.users.index') }}" title="Admin Users">{{ __('Users') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-danger" href="{{route('admin.packages.index')}}" title="Admin Packages">{{ __('Packages') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-danger" href="{{route('admin.equipment.index')}}" title="Admin Equipment">{{ __('Equipment') }}</a>
                    </li>
                @endcan
                @can('maker')
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('authed.equipment.index') }}">{{ __('Equipment') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('authed.packages.index') }}">{{ __('Shipped Items') }}</a>
                    </li>
                @endcan
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            <img src="{{auth()->user()->sm_profile_image_url}}" alt="Profile image" class="rounded-circle" />

                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('authed.user.profile') }}">
                                {{ __('Profile') }}
                            </a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>